-- CREATE faqs main table
CREATE TABLE `faqs`
(
  `id`              int(11) unsigned NOT NULL AUTO_INCREMENT,
  `faq_category_id` int(11) unsigned NOT NULL,
  `question`        varchar(255)     NOT NULL DEFAULT '',
  `answer`          text             NOT NULL,
  `order`           int(11) unsigned          DEFAULT NULL,
  `created_at`      datetime                  DEFAULT NULL,
  `updated_at`      datetime                  DEFAULT NULL,
  `deleted_at`      datetime                  DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `faq_category_id_index` (`faq_category_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;

-- CREATE faq_categories table
CREATE TABLE `faq_categories`
(
  `id`         int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name`       varchar(80) DEFAULT NULL,
  `slug`       varchar(80) DEFAULT NULL,
  `created_at` datetime    DEFAULT NULL,
  `updated_at` datetime    DEFAULT NULL,
  `deleted_at` datetime    DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
-- Insert default faq categories

INSERT INTO `faq_categories` (`id`, `name`, `slug`, `created_at`, `updated_at`, `deleted_at`)
VALUES (1, 'GENERAL', 'general', '2019-01-23 12:14:40', '2019-01-23 12:14:40', NULL),
       (2, 'SWEEPSTAKES', 'sweepstakes', '2019-01-23 12:14:40', '2019-01-23 12:14:40', NULL),
       (3, 'PUBLICIST', 'publicist', '2019-01-23 12:14:40', '2019-01-23 12:14:40', NULL),
       (4, 'JOURNALIST', 'journalist', '2019-01-23 12:14:40', '2019-01-23 12:14:40', NULL);

-- Insert some faqs with the related category
INSERT INTO `faqs` (`id`, `faq_category_id`, `question`, `answer`, `order`, `created_at`, `updated_at`, `deleted_at`)
VALUES (1, 1, 'What is OnePitch?',
        'OnePitch is the PR industry’s first email pitch platform that matches pitches to journalists’ preferences through a specific categorization and vetting process.',
        1, '2019-01-22 11:41:22', '2019-01-22 11:41:22', NULL),
       (2, 1, 'How does OnePitch exactly work?',
        'Publicists upload and categorize their pitches based on select “topics” and “industries.” Journalists select the same “topics” and “industries” within their profiles. Once pitches have been submitted, OnePitch sends ONE email a day of the pitches that matches journalists’ exact topics and industries. Journalists have the option to contact the publicist directly from their OnePitch emails if desired.\n\nJournalists can also upload an inquiry if they’re looking for sources on a particular topic. Similar to the pitch, journalists categorize their inquiry based on select “topics” and “industries.” Publicists select the same “topics” and “industries” to subscribe to within their profile relevant to their brand or client. From there, OnePitch sends out ONE email a day of the inquiries that match a publicists’ exact topics and industries. Publicists can contact the journalist directly from their OnePitch email.',
        2, '2019-01-22 11:41:22', '2019-01-22 11:41:22', NULL),
       (3, 1, 'How is OnePitch different from a press release?',
        'OnePitch is strictly a pitching platform. Pitches loaded by publicists have a simple format and there is no uploading of press releases, either. Journalists can contact publicists for more info if they want.',
        3, '2019-01-22 11:49:08', '2019-01-22 11:49:08', NULL),
       (4, 1, 'Does OnePitch provide a media database?',
        'No way, Jose. OnePitch will always keep the identity of journalists’ private.', 4, '2019-01-22 11:49:08',
        '2019-01-22 11:49:08', NULL),
       (5, 1, 'Does OnePitch guarantee my pitch is received and responded to?',
        'There is no guarantee every pitch will be sent to a journalist. If there are no “matches” for a pitch, then the OnePitch team will notify the publicist via email, and follow up once a “match” has been found.',
        5, '2019-01-22 11:49:08', '2019-01-22 11:49:08', NULL),
       (6, 1, 'Can I access OnePitch on a mobile app?',
        'Sorry but not yet. We’re sticking strictly to a web app for now, but you can access OnePitch through a mobile browser.',
        6, '2019-01-22 11:49:08', '2019-01-22 11:49:08', NULL),
       (7, 1, 'Do I have to agree to the Terms of Use and Rules to join OnePitch?',
        'Yes. We require all users who join the platform to read and agree to the Terms of Use and Rules. Our lawyers said so.',
        7, '2019-01-22 11:49:08', '2019-01-22 11:49:08', NULL),
       (8, 1, 'What if I need more help?',
        'Send us an email: <a mailto:info@onepitch.co>info@onepitch.co</a> or head to our contact page: <a href=\"https://onepitch.co/contact\"> https://onepitch.co/contact </a>.',
        8, '2019-01-22 11:49:08', '2019-01-28 20:58:59', NULL),
       (9, 1, 'This is the best thing EVER. How can I tell others?',
        'Head to <a href=\"https://onepitch.co/refer\">https://onepitch.co/refer</a> to sign up and obtain your shareable referral link. You can also access your referral link at any time in your profile.',
        9, '2019-01-22 11:49:08', '2019-01-28 21:03:32', NULL),
       (10, 1, 'What’s with the typewriter logo?',
        'A lot of great stories started on typewriters. We wanted to give them props.', 10, '2019-01-22 11:49:08',
        '2019-01-22 11:49:08', NULL),
       (11, 1, 'This is the best thing EVER. How can I tell others?',
        'We believe in simplicity: That’s why we designed a tool that delivers one email, once a day. \n\nWe believe in the power of the press: Progress in modern society happens when press is free and robust. That’s why we support the community of journalists. \n\nWe believe in NOT wasting time: Ain’t nobody got time for that. That’s why our tool matches precisely what journalists and publicists need from each other.',
        11, '2019-01-22 11:49:08', '2019-01-22 11:49:08', NULL),
       (12, 2, 'How do I enter the monthly referral sweepstakes?',
        'Every user must agree to our <a href=\"https://onepitch.co/terms\">Terms of Use</a>, <a href=\"https://onepitch.co/privacy\">Privacy Policy</a> and <a href=\"https://onepitch.co/refer\">Sweepstakes Rules</a> to sign up and create a profile.  After you’ve agreed, you’ll need to confirm your account before you can access your unique referral link.',
        1, '2019-01-22 11:57:00', '2019-01-28 21:05:21', NULL),
       (13, 2, 'Where can I find my unique referral link?',
        'Head to <a href=\"https://onepitch.co/profile\">https://onepitch.co/profile</a> to find your shareable referral link. You can also view the Referral Sweepstakes page for more info: <a href=\"https://onepitch.co/refer\">https://onepitch.co/refer</a>.',
        2, '2019-01-22 11:57:00', '2019-01-28 21:06:12', NULL),
       (14, 2,
        'Am I limited to only inviting people whom belong my user base (i.e. publicists can only invite publicists)?',
        'Hell nah! Invite all your media friends including editors, journalists, reporters, and freelancers. Just be sure they’re legit media people because we don’t accept everyone who signs up as a journalist.',
        3, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (15, 2, 'What the heck do I win?',
        'The winner of the monthly sweepstakes will win a cash prize of $100 delivered via check, PayPal, or Venmo. Yeah, we’re totally serious. So get to referring!',
        4, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (16, 2, 'When does the sweepstakes begin?',
        'We start accepting sweepstakes entries on the first day of each month starting at 12am PST. Remember: this is a monthly thing!',
        5, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (17, 2, 'When does the sweepstakes end?',
        'The sweepstakes ends on the last day of each month at 11:59pm PST. If you don’t win in May, who knows, you could win in June!',
        6, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (18, 2, 'How is the winner chosen?',
        'Winners are selected at random on the second day of the following month. For example, if you’ve won the February sweepstakes, then you’ll be notified on March 2nd.',
        7, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (19, 2, 'How do I claim my prize?',
        'Winners are notified on the second day of the month when the initial selection is made and are sent a reminder within 5 days of the first notification. If a winner fails to claim their prize within 7 days of the initial notification, the prize may be forfeited and an alternate winner selected.',
        8, '2019-01-22 11:57:00', '2019-01-22 11:57:00', NULL),
       (20, 3, 'How does One Pitch benefit me as a publicist?',
        'OnePitch saves you time and energy spent conducting research, scouring media databases, building media lists, pitching media AND following-up, and typically never even receiving a “yes” or “no.” With OnePitch, you can upload a pitch and expect the most ideal media contact to receive it in their Daily OnePitch email.',
        1, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (21, 3, 'Why is there 1 bullet to explain WHAT my pitch is about?',
        'Explain WHAT it is you’re pitching. Media don’t want to read a novel, nor do they like your fUnky Formatting. Give it your best shot.',
        2, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (22, 3, 'How come I only have up to 3 bullets to explain WHY my pitch is important?',
        'You’re required to fill in at least one bullet and no more than three. Trust us, you’ll grow to appreciate this format as will your BFF media contacts.',
        3, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (23, 3, 'How come I can only select 5 topics max?',
        'We limit the number of topics because the most successful pitches have included no more than 5 topics max. Select the MOST relevant topics related to your pitch. Trust us on this.',
        4, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (24, 3, 'What if I don’t see a topic listed that relates to my pitch?',
        'Don’t worry, we have a field titled “Suggested Topic” where you can enter a topic of your choice. It will be included on your pitch, however.',
        5, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (25, 3, 'How come I can only select 5 industries max?',
        'We limit the number of industries because the most successful pitches have include no more than 5 industries. Select the MOST relevant industries related to the brand. This helps journalists identify why the brand is a good fit for their outlet/pubication.',
        6, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (26, 3, 'My pitch has been confirmed and approved. Now what?',
        'Sit back and let OnePitch works its magic. Once a journalist receives your pitch in their daily email, they’ll get in touch if they’re interested in pursuing. It’s that simple.',
        7, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (27, 3, 'When should I expect a journalist to receive my pitch email?',
        'Pitches must be submitted by 5pm PST to be sent the following day. We do our best to confirm and approve all pitches ASAP, and this helps us ensure your pitch is relevant for only the most ideal media contact(s). All pitch emails are sent starting at 5am PST.',
        8, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (28, 3, 'Why can’t I view the journalist’s name or contact info?',
        'Because we believe that sending numerous emails, calls, and tweets to journalists is not the answer to securing a great media placement. Great stories start with building a relationship. OnePitch is the first step.',
        9, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (29, 3, 'Why can’t I send a follow up?',
        'With OnePitch, there’s no need. You can expect your pitch to end up in the right hands. And besides, media folks DON’T like being bombarded with follow ups.',
        10, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (30, 3, 'What if a journalist doesn’t respond to my pitch?',
        'We like to think no pitch will go unanswered. If someone doesn’t respond to your pitch, then don’t take it personal. Sometimes great stories need time to develop.',
        11, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (31, 3, 'How come my pitch was declined?',
        'Sometimes folks don’t always enter the correct info. Maybe the company isn’t actually a company, or maybe your WHAT bullets about Autonomous Cars refer to the latest viral video about a bionic third arm. Either way, something wasn’t right and it was flagged by our team. Don’t worry, we’ll contact you to make sure your pitch is confirmed, approved and sent ASAP.',
        12, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (32, 3, 'How do I know where to look for a response to my pitch?',
        'Most pitch responses will arrive via email. However, keep in mind you may have also included your phone number and social media links. We always recommend paying close attention to your direct message folders, and consider answering those unknown callers. You never know who could be on the other line!',
        13, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (33, 3, 'A journalist responded to my pitch. Now what?',
        'Our work here is done, and now it’s up to you how you proceed with your new contact. Since the journalist responded expressing interest, you now have access to their name, email, and outlet or publication. Aside from having a new relationship!',
        14, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (34, 3, 'What if I see my pitch was published in an article, but I never received a response from a journalist?',
        'Chances are the journalist was able to use the information provided to write the story. This happens, unfortunately, and we do our best to notify everyone of connections and placements that occur through OnePitch.',
        15, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (35, 3, 'I need to edit my pitch and don’t know how. Help!',
        'Don’t worry. We’re all human and realize change is inevitable, as well as a client who likes to abruptly change the launch date. If your pitch needs to be edited,  once confirmed, you can click your confirmation email or head to your pitch log to update. If your pitch has been approved already, then you must contact <a href=\"mailto:info@onepitch.co\">info@onepitch.co</a> with the changes you need made.',
        16, '2019-01-22 16:29:48', '2019-01-28 21:07:32', NULL),
       (36, 3, 'Can I resend my pitch after it’s been sent?',
        'Pitches submitted through OnePitch are only sent once. If you want to re-submit we recommend waiting at least one week, and require that no more than 2 pitches of the same content be submitted within a month period.',
        17, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (37, 3, 'Can I edit my pitch after it’s been sent?',
        'No. Once you submit your pitch and it’s approved by the OnePitch admin team, it can no longer be edited.', 18,
        '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (38, 3, 'Where can I see who received my pitch?',
        'After your pitch has been sent, you can locate the “Status” column in your pitch log to view the number of recipients. We do not share names or publications to preserve the identify of the media contacts.',
        19, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (39, 3, 'How can I Subscribe to a journalist Inquiry?',
        'Click the <a href=\"https://onepitch.co/publicist/interests\">Subscribe to Inquiry</a> button in your profile, or click the pencil icon next to “Industries and Topics.” From there select an industry related to your brand or client, and then select the relevant topics they can be a source for. Each industry requires a separate subscription but you can easily replicate the topics across multiple industries.',
        20, '2019-01-22 16:29:48', '2019-01-28 21:09:32', NULL),
       (40, 3, 'Can I choose when I want to receive an inquiry?',
        'Easy. Head to your profile and scroll to the bottom where you’ll find “Daily Mail Time Settings.” Select your preferred time zone and time, and click SAVE CHANGES.',
        21, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (41, 3, 'Can I view inquiries I’ve received in the past?',
        'Yes! Head to your OnePitch profile dashboard and find your Inquiry History Log which lists each inquiry you’ve received in your daily email.',
        22, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (42, 3, 'Can I save inquiries and respond to them later?',
        'Sure can. Beneath each inquiry in your daily email, click SAVE INQUIRY to save inquiries within your OnePitch profile dashboard which you can view and respond to directly from your profile.',
        23, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (43, 3, 'What is ‘Add New Brand’ at the top of my profile dashboard?',
        'This feature is known as the Brand Index. Journalists can use the Brand Index to search for and contacts brands as well as sources. Make sure when you add your brands all the information provided is accurate and up to date.',
        24, '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (44, 3, 'Can I edit or delete a brand after I’ve added it to the Brand Index?',
        'Locate the Brand Index on your OnePitch profile dashboard and click the name of the brand.', 25,
        '2019-01-22 16:29:48', '2019-01-22 16:29:48', NULL),
       (45, 3,
        'How do I update my profile info including password, photo, email, phone number, social media links, and brand or agency?',
        'Easy. Head to your <a href=\"https://onepitch.co/profile\">profile</a> and click the pencil icon above your profile photo.',
        26, '2019-01-22 16:29:48', '2019-01-28 21:10:15', NULL),
       (46, 3, 'How do I reset my password or update my profile image?',
        'Simple. Head to your <a href=\"https://onepitch.co/profile\">profile</a> and click the drop down menu next to your profile photo, or click the navigation menu in the upper left corner of the page.',
        27, '2019-01-22 16:29:48', '2019-01-28 21:10:50', NULL),
       (47, 3, 'Can I unsubscribe to the OnePitch Onesie monthly newsletter?',
        'Yep-sure can! You can unsubscribe at any time by heading to your <a href=\"https://onepitch.co/profile\">profile</a> and clicking the pencil icon above your profile photo.',
        28, '2019-01-22 16:29:48', '2019-01-28 21:11:21', NULL),
       (48, 3, 'How can I invite my co-workers, other PR professionals, friends or Aunt Jane to join?',
        'Head to <a href=\"https://onepitch.co/profile\">https://onepitch.co/profile</a> to find your shareable referral link.',
        29, '2019-01-22 16:29:48', '2019-01-28 21:11:46', NULL),
       (49, 4, 'How does OnePitch benefit me as a journalist?',
        'OnePitch is the only private, non-invasive pitch-only platform for journalists and the media at large. It requires no interaction on-site other than creating a profile and selecting your preferred interests. You’ll only get ONE email of the pitches that match EXACTLY to your preferences a day.',
        1, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (50, 4, 'When should I expect to receive my OnePitch daily pitch email?',
        'All OnePitch emails send between 5am and 2pm PST. Head to your profile settings to select your preferred time zone and time to ensure pitches hit your inbox when you want them to. If you do not select a timezone or time, then you will receive pitches at 5am PST each day.',
        2, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (51, 4, 'Why haven’t I received a Daily OnePitch pitch email?',
        'If you haven’t received a Daily OnePitch email yet chances are there are no matches for your selected interests. If you know someone who covers a specific topic and/or industry, head to <a href=\"https://onepitch.co/refer\">https://onepitch.co/refer</a> and send them your unique referral link to join!',
        3, '2019-01-22 19:00:19', '2019-01-28 21:12:27', NULL),
       (52, 4, 'Why don’t I receive multiple Daily OnePitch pitch emails?',
        'Currently, OnePitch sends one daily email to all journalists. We’re keeping things simple.', 4,
        '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (53, 4, 'How do I respond to a publicists’ pitch?',
        'At the end of each publicists’ pitch there is a link to “Email Publicist” to pursue the pitch opportunity. You can click the link and an email will auto-populate. No need to log back into OnePitch or anything annoying like that.',
        5, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (54, 4, 'Can I view pitches I’ve received in the past?',
        'Yes! Head to your OnePitch profile dashboard and find your Pitch History Log which lists each pitch you’ve received in your daily email.',
        6, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (55, 4, 'Can I save pitches and respond to them later?',
        'Sure can. Beneath each pitch in your daily email, click SAVE PITCH to save pitches within your OnePitch profile dashboard. Once your pitch is saved you can view and respond to it directly from your profile.',
        7, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (56, 4, 'How do I create an inquiry?',
        'Simple. Head to your profile and click “CREATE NEW INQUIRY” to begin crafting your inquiry. Specify who you are, where you work, and what you’re inquiring about. Then explain what you want and need in order to create your story, followed by categorizing your inquiry to ensure it lands in the hands of the most optimal source.',
        8, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (57, 4, 'Can I edit an inquiry after it’s been sent?',
        'No. Once you submit your inquiry and it’s approved by the OnePitch admin team, it can no longer be edited.', 9,
        '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (58, 4, 'What if a publicist doesn’t respond to my inquiry?',
        'We like to think no journalist inquiry will go unanswered. If someone doesn’t respond to your initial email, then they probably shouldn’t have a career in PR.',
        10, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (59, 4, 'What is the Brand Index?',
        'The Brand Index is a searchable index of brands and sources. As a journalist you can search for brand names, keywords and terms, individuals’ names, and company names. You can also filter the results by Industry and/or Topic.',
        11, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (60, 4, 'How can I contact a brand using the Brand Index?',
        'Easy. You can click any of the icons beneath the contact name and company name including Twitter, LinkedIn, phone and email.',
        12, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (61, 4, 'Why was my account declined?',
        'There are a number of reasons users aren’t allowed access. If you think you should be allowed in, send a message to <a href=\"mailto:info@onepitch.co\">info@onepitch.co</a>, or fill out our contact form: <a href=\"https://onepitch.co/contact\">https://onepitch.co/contact</a>.',
        13, '2019-01-22 19:00:19', '2019-01-28 21:13:00', NULL),
       (62, 4, 'How do I update my writing interests (i.e. my pitch subscriptions)?',
        '<li>\n                            Head to your OnePitch <a href=\"https://onepitch.co/profile\">https://onepitch.co/profile</a> dashboard and click SUBSCRIBE TO PITCHES at the top of your profile, or find the pencil icon to the right of SUBSCRIBE TO PITCHES within your OnePitch profile dashboard to update your writing interests.\n                            <ul>\n                                <li>To update the specific topics related to an industry, click on the industry, and you’ll be directed to the topic selection page. Once your topic selections are complete, click ‘NEXT’ at the bottom of the page.</li>\n                            </ul>\n                        </li>\n                    </ul>',
        14, '2019-01-22 19:00:19', '2019-01-28 21:13:45', NULL),
       (63, 4, 'Can I choose when I want to receive my OnePitch daily email?',
        'Easy. Head to your profile and scroll to the bottom where you’ll find “Daily Mail Time Settings.” Select your preferred time zone and time, and click SAVE CHANGES.',
        15, '2019-01-22 19:00:19', '2019-01-22 19:00:19', NULL),
       (64, 4,
        'How do I update my profile info including password, photo, email, social media links, and publication or outlet?',
        'Easy. Head to your <a href=\"https://onepitch.co/profile\">profile</a> and click the pencil icon above your profile photo.',
        16, '2019-01-22 19:00:19', '2019-01-28 21:15:03', NULL),
       (65, 4, 'How do I reset my password or update my profile image?',
        'Simple. Head to your <a href=\"https://onepitch.co/profile\">profile</a> and click the drop down menu next to your profile photo, or click the navigation menu in the upper left corner of the page.',
        17, '2019-01-22 19:00:19', '2019-01-28 21:15:37', NULL),
       (66, 4, 'Can I unsubscribe to the OnePitch Daily pitch emails?',
        'Yep-sure can! You can unsubscribe at any time by heading to your profile and clicking the pencil icon above your <a href=\"https://onepitch.co/profile\">profile</a> photo. Please note journalists DO NOT receive any promotional emails from OnePitch.',
        18, '2019-01-22 19:00:19', '2019-01-28 21:16:04', NULL),
       (67, 4, 'How can I invite my fellow journalists, reporters, editors or Uncle John to join?',
        'Head to <a href=\"https://onepitch.co/profile\">https://onepitch.co/profile</a> to find your shareable referral link.',
        19, '2019-01-22 19:00:19', '2019-01-28 21:16:31', NULL);