CREATE OR REPLACE VIEW vw_user_analytics AS
SELECT id                AS id,
       role              AS role,
       full_name         AS full_name,
       company           AS company,
       email             AS email,
       username          AS username,
       phone_number      AS phone_number,
       linkedin_id       AS linkedin_id,
       twitter_id        AS twitter_id,
       photo             AS photo,
       twitter_url       AS twitter_url,
       linkedin_url      AS linkedin_url,
       hear_about        AS hear_about,
       hear_about_other  AS hear_about_other,
       subscribe         AS subscribe,
       agree_tos         AS agree_tos,
       referral_hash     AS referral_hash,
       referral_id       AS referral_id,
       is_verified       AS is_verified,
       verification_code AS verification_code,
       created_at        AS created_at,
       updated_at        AS updated_at,
       last_login        AS last_login,
       is_admin          AS is_admin,
       approved          AS approved,
       has_industry      AS has_industry
FROM users
;